### ISSUE TITLE
A way to disable smartlock via options to FlutterAuthUi.startUi

### ISSUE THREAD

**Issue by jonsutherland** [koji-1009/flutter_auth_ui#17]
Can we have a way to disable smart lock as an option passed in to the startUi method or something?  Eg. configurable option for setIsSmartLockEnabled?

`
private final Intent signIn = AuthUI.getInstance()
        .createSignInIntentBuilder().setIsSmartLockEnabled(false)
        .setAvailableProviders(providers)
        .build();
`

**Comment by koji-1009** [comment]
Hi @jonsutherland , I added `enableSmartLockForAndroid` option.

https://github.com/koji-1009/flutter_auth_ui/blob/1.0.0/lib/flutter_auth_ui.dart#L109

**Comment by jonsutherland** [comment]
Thank you very much, that will do it.
