### ISSUE TITLE
Disable first and lastname at email registration

### ISSUE THREAD

**Issue by PegasusPool** [koji-1009/flutter_auth_ui#19]
Is it possible to not show the name field at registration for AuthUiItem.AuthEmail type registrations?

**Comment by PegasusPool** [comment]
Looks like there is a method: https://github.com/firebase/FirebaseUI-Android/blob/735bf7b00501542f7af2e18bc9a8fc8308ed35d6/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L712

**Comment by koji-1009** [comment]
code
Android: https://github.com/firebase/FirebaseUI-Android/blob/7.1.1/auth/src/main/java/com/firebase/ui/auth/AuthUI.java#L712
iOS : https://github.com/firebase/FirebaseUI-iOS/blob/v9.0.0/EmailAuth/FirebaseEmailAuthUI/FUIEmailAuth.h#L71

issues
Android: https://github.com/firebase/FirebaseUI-Android/issues/467
iOS: https://github.com/firebase/FirebaseUI-iOS/issues/245

**Comment by koji-1009** [comment]
I published v1.1.1.
I added the `requireName` option.

https://pub.dev/packages/flutter_auth_ui/versions/1.1.1
