### ISSUE TITLE
Customize app bar title?

### ISSUE THREAD

**Issue by alekbarszczewski** [koji-1009/flutter_auth_ui#25]
Right now app bar title on android is "ui_flow" which looks weird.
Not sure yet how it works on ios.
Is there any option to customize it?
Also if it was possible to customize app bar color that would be awesome too.

<img width="419" alt="Android_Emulator_-_Pixel_3a_API_30_x86_5554" src="https://user-images.githubusercontent.com/2742373/107348985-fbc59c00-6ac7-11eb-846d-fcdbb0950f0e.png">

**Comment by koji-1009** [comment]
Hi, @alekbarszczewski.

I suggest you to add `app_name` value at your project's string resource on Android.
https://github.com/firebase/FirebaseUI-Android/pull/813

Sample code is here.
https://github.com/koji-1009/flutter_auth_ui/blob/change_appbar_title/example/android/app/src/main/res/values/strings.xml

This behavior is highly dependent on the Firebase Auth-Android implementation and is subject to change in the future.

---

I haven't started developing the feature to change the color of the appbar.
If you have a good idea, please PR 😄

**Comment by koji-1009** [comment]
@alekbarszczewski .
I added `Tips` to README file.

---

In my environment, I can change AppBar colors.
If you want, change color value as `colorPrimary` and `colorPrimaryDark` to your app's `colors.xml` file.
However, this operation may affect libraries that call other Android UIs, so please test it thoroughly.

**Comment by alekbarszczewski** [comment]
Thank you! app_name works, I will experiment with colors.
