### ISSUE TITLE
Module 'flutter_auth_ui' not found

### ISSUE THREAD

**Issue by jindalAnuj** [koji-1009/flutter_auth_ui#38]
Ios app running fine but building archive throws error "Module 'flutter_auth_ui' not found"

**Comment by koji-1009** [comment]
Hi, @jindalAnuj.

Could you check this issue and comments?
https://github.com/flutter/flutter/issues/53573#issuecomment-757165986

**Comment by jindalAnuj** [comment]
@koji-1009 when tried to build with `flutter build ios` 

i got this error.

`    ld: symbol(s) not found for architecture armv7`

but when i run on xcode it gives module not found . Is this related to flutter auth ui for web 
Please see this https://github.com/LinusU/flutter_web_auth/issues/18#issue-574822284

**Comment by koji-1009** [comment]
Umm, this repository is not related to `flutter_web_auth` plugin.
I'm sorry but I don't know the details of the problem, could you check https://github.com/flutter/flutter/issues/46610#issuecomment-577484354?

What version of flutter_auth_ui are you using?
If you are using `1.2.1`, try upgrading to `1.2.2` or downgrading to `1.2.0`.

**Comment by jindalAnuj** [comment]
Yes already checked that and i am using 1.3.0 version

Sent from Yahoo Mail on Android 
 
  On Sat, 27 Feb 2021 at 12:01 pm, Koji Wakamiya<notifications@github.com> wrote:   


Umm, this repository is not related to flutter_web_auth plugin.
I'm sorry but I don't know the details of the problem, could you check flutter/flutter#46610 (comment)?

What version of flutter_auth_ui are you using?
If you are using 1.2.1, try upgrading to 1.2.2 or downgrading to 1.2.0.

**Comment by koji-1009** [comment]
Is the minimum support version of iOS 12 or higher?

**Comment by jindalAnuj** [comment]
@koji-1009  Yes i have minimum sdk version 12 in podfile and target sdk.

**Comment by koji-1009** [comment]
Does your project use Swift?

**Comment by jindalAnuj** [comment]
@koji-1009  please check my above comment i have updated it. Yes i think i am using swift 
![Screenshot 2021-02-27 at 12 52 08 PM](https://user-images.githubusercontent.com/31108317/109378693-a0364380-78fa-11eb-9e88-1bc522009c72.png)

**Comment by koji-1009** [comment]
I think there is a problem with the processing related to CocoaPods, but if deleting the Podfile.lock or Pods directory does not solve the problem, I can't think of a solution.
Sorry.

**Comment by jindalAnuj** [comment]
Thanks for your help. I am trying arm64 in active build only lets see what will happen

**Comment by jindalAnuj** [comment]
The issue got resolved . The main issue is that I was testing on 11.3.3 version of Xcode , due to which archiving was throwing the error as apple has updated some terms which resulted in these errors .
For any other who is facing archiving issue on xcode please refer to this https://stackoverflow.com/a/66417812/9568449 .
Which clearly indicate the certificates issue.
