### ISSUE TITLE
Error management

### ISSUE THREAD

**Issue by jeanmatthieud** [koji-1009/flutter_auth_ui#44]
Currently, when the login fails, it is not possible to know why.

In the [Android documentation](https://firebase.google.com/docs/auth/android/firebaseui#sign_in), it's possible to retrieve an error code :
```java
@Override
protected void onActivityResult(int requestCode, int resultCode, Intent data) {
    super.onActivityResult(requestCode, resultCode, data);

    if (requestCode == RC_SIGN_IN) {
        IdpResponse response = IdpResponse.fromResultIntent(data);

        if (resultCode == RESULT_OK) {
            // Successfully signed in
            FirebaseUser user = FirebaseAuth.getInstance().getCurrentUser();
            // ...
        } else {
            // Sign in failed. If response is null the user canceled the
            // sign-in flow using the back button. Otherwise check
            // response.getError().getErrorCode() and handle the error.
            // ...
        }
    }
}
```

After digging a little bit more, it's even possible to retrieve a lot more data, within the `IdpResponse` object.
In my case, I need to merge data between accounts, when the user goes from an account to another (ie. anonymous users).
I'm currently doing it manually, as I recreated the a lot of the login UI.
To be able to do that with `flutter_auth_ui`, I need the `IdpResponse` content, and not only a boolean as a result.

I believe it's also possible with iOs, but I'm not good in ObjC or Swift lol
```swift
func authUI(_ authUI: FUIAuth, didSignInWith user: FIRUser?, error: Error?) {
  // handle user and error as necessary
}
```

Is it possible to implement a callback with the full auth result ?

**Comment by koji-1009** [comment]
> Is it possible to implement a callback with the full auth result ?

Probably possible.
Returning a bool is to simplify the implementation of the plugin. (Because this project is not official one...)

I need to think about 3 platforms of Android/iOS/Web, so can I consider it for a few days?

**Comment by jeanmatthieud** [comment]
Thank you for taking the time to consider it :)

**Comment by koji-1009** [comment]
- Android
  - https://github.com/firebase/FirebaseUI-Android/blob/7.1.1/auth/src/main/java/com/firebase/ui/auth/IdpResponse.java#L324
- iOS
  - https://firebase.google.com/docs/reference/swift/firebaseauth/api/reference/Type-Definitions#/c:FIRAuth.h@T@FIRAuthResultCallback
- Web
  - https://github.com/firebase/firebaseui-web/blob/v4.8.0/types/index.d.ts#L199

**Comment by jeanmatthieud** [comment]
In the app code, to manage the (Flutter) error code `account-exists-with-different-credential`, we need to retrieve the credentials associated to the error ([documentation / source code](https://firebase.flutter.dev/docs/auth/error-handling/#handling-account-exists-with-different-credential-errors)).

It seems possible with the Android `IdpResponse` object, and the Web `AuthUIError` object.
I'm not an iOs developer, but it doesn't seems to be the case with the `FIRAuthResultCallback` callback.

To have a better integration with FirebaseUI iOs/Android/Web libs, shouldn't we use the callbacks from the librairies instead of the callbacks from Firebase Auth itself ?
For Android, it's the example I gave in the issue description, and it will be trivial to add to your code.
For iOs, [I'm a little lost](https://firebase.google.com/docs/auth/ios/account-linking#link-auth-provider-credentials-to-a-user-account).

I'm more used to use the Flutter Auth packages than the native ones. I'm not sure if the error codes are exactly the same, or if a mapping is required.

**Comment by koji-1009** [comment]
I'm sorry if it's different, but do you think `flutter_auth_ui` calls `firebase_auth` in Dart code?

This library does not access `firebase_auth` in Dart code.
https://github.com/koji-1009/flutter_auth_ui/blob/2.0.0/flutter_auth_ui/lib/flutter_auth_ui.dart#L136
`firebase_auth` is included in dependencies because it depends on the runtime, but I may be able to remove it.

This library calls the FirebaseUI of each platform(iOS/Android/Web) through the method channel.
As far as I can see, `firebase_auth` doesn't have a callback that returns any associated credentials and errors, so I need to return the error information from native SDK.

I think that it may be difficult to implement due to such circumstances.
If there is an easier way, I'm waiting for PR :)

**Comment by jeanmatthieud** [comment]
> I'm sorry if it's different, but do you think `flutter_auth_ui` calls `firebase_auth` in Dart code?
Don't be sorry, it's another way of getting auth UI working :)

> This library does not access `firebase_auth` in Dart code.
> https://github.com/koji-1009/flutter_auth_ui/blob/2.0.0/flutter_auth_ui/lib/flutter_auth_ui.dart#L136
> `firebase_auth` is included in dependencies because it depends on the runtime, but I may be able to remove it.
> 
> This library calls the FirebaseUI of each platform(iOS/Android/Web) through the method channel.
> As far as I can see, `firebase_auth` doesn't have a callback that returns any associated credentials and errors, so I need to return the error information from native SDK.
That's what I had in mind.

> I think that it may be difficult to implement due to such circumstances.
> If there is an easier way, I'm waiting for PR :)
I personally never developed a bridge between native and dart code, and I currently don't have the time to work on it :(

**Comment by koji-1009** [comment]
Since the official plugin development is in progress, I expect that it will be supported there and not in this repo.
Thanks.

https://github.com/FirebaseExtended/flutterfire/discussions/5549
