### ISSUE TITLE
How can I retrieve the user id?

### ISSUE THREAD

**Issue by WalterLievens** [koji-1009/flutter_auth_ui#49]
Hi,

in the example method `FlutterAuthUi.startUi()` is used resulting in a boolean.

But how can I retrieve the user id?
Currently, I use another package _firebase_auth_ui_ but since it's not updated anymore and I would like to have null safety, I'm looking for an alternative. But that package returns the uid that I use to store the data of the logged in user.

Any pointers how I can do this with flutter_auth_ui?

**Comment by koji-1009** [comment]
How about calling a `FirebaseAuth.instance.currentUser?.uid` after getting the `result`?

**Comment by WalterLievens** [comment]
Thanks for your swift reply, I didn't realise I had to use FirebaseAuth!

I'm still struggling a bit to retrieve the current user directly after calling `FlutterAuthUi.startUi` since Firebase needs to time to initialise the current user. But thanks to https://stackoverflow.com/questions/64520543/struggling-with-authstatechanges-in-flutter I should be able to rewrite my app.

I think it might be worthwhile to mention `FirebaseAuth.instance.currentUser` (and maybe also the associated `FirebaseAuth.instance.onAuthStateChanged`) in the Example and/or documentation?

**Comment by koji-1009** [comment]
Maybe, you can use `await FirebaseAuth.instance. authStateChanges().first()`.
Could you take a look at [this official document](https://firebase.flutter.dev/docs/auth/usage/#authentication-state)?

`firebase_auth` lib is more common than `flutter_auth_ui` lib.
So, there are no plans to add documentation for `FirebaseAuth.instance`.

Thanks.

**Comment by WalterLievens** [comment]
Sure, no prob, I manage to make it work now.

I was just saying that, with looking at your example `final result = await FlutterAuthUi.startUi` I didn't realise I also needed to use the library of FirebaseAuth itself to retrieve the user (status).

Kudus for your library, it's very useful!
