### ISSUE TITLE
Widget enhancement request

### ISSUE THREAD

**Issue by compass-codeworks** [koji-1009/flutter_auth_ui#54]
Can a widget be made that would allow embedding the login screen inside the UI instead of launching via a future?

**Comment by koji-1009** [comment]
Unfortunately I can't.
Especially the web implementation is impossible.

Please wait for the development by the firebase team.
That is needed a FirebaseUI written in Dart for Flutter.
https://github.com/FirebaseExtended/flutterfire/issues/789

**Comment by compass-codeworks** [comment]
Worth a shot. Thanks for the info.
