### ISSUE TITLE
accesstoken, logout sample

### ISSUE THREAD

**Issue by sowsan** [koji-1009/flutter_auth_ui#55]
First, thank you so much for publishing this plugin!

How we can get the accesstoken to send it back to protected APIs?

Also, is there an example including logout ?

**Comment by koji-1009** [comment]
Hi, @sowsan.

> How we can get the accesstoken to send it back to protected APIs?

Do you mean the [IDP token](https://github.com/firebase/FirebaseUI-Android/blob/7.1.1/auth/src/main/java/com/firebase/ui/auth/IdpResponse.java#L218)? 
I'm sorry, I haven't created an API to get it.

> Also, is there an example including logout ?

How about call `FirebaseAuth.instance.signOut()`?
