### ISSUE TITLE
Xcode 12.1 build gets definition conflicts error.

### ISSUE THREAD

**Issue by esoyyigit** [koji-1009/flutter_auth_ui#61]
Hi, I am trying to build iOS, but Xcode gives following error,

`
/flutter_auth_ui-2.2.1/ios/Classes/SwiftFlutterAuthUiPlugin.swift:83:17: error:
    definition conflicts with previous value
                let url = URL(string: link) else {
`

**Comment by koji-1009** [comment]
Oops, I'm sorry. I will investigate soon.

**Comment by koji-1009** [comment]
I published v2.2.2!

**Comment by esoyyigit** [comment]
yes, it is working now. Thanks
