### ISSUE TITLE
How to use this plugin after user signup

### ISSUE THREAD

**Issue by ArbitRandomUser** [koji-1009/flutter_auth_ui#62]
Great library , the only one that i got working without hassle on flutter 2.0
i saw your medium post, you have specified there is no way to get user information.
how are you using this to login the user ? i mean can i use other flutterfire libraries directly after the user login ?

**Comment by koji-1009** [comment]
> i mean can i use other flutterfire libraries directly after the user login ?

Yes, try checking your login status with firebase_auth.

**Comment by ArbitRandomUser** [comment]
You have mentioned that sign out hasn't been implemented,
Will FirbaseAuth.instance.signOut() work though ?

**Comment by ArbitRandomUser** [comment]
okay i just went through some closed issues, its been mentioned there , 
thanks though
