### ISSUE TITLE
Logo for iOs

### ISSUE THREAD

**Issue by robmr88** [koji-1009/flutter_auth_ui#69]
Hi! would it be possible to have the logo for iOs too?
Thanks

**Comment by koji-1009** [comment]
Hi, @robmr88!

Sorry, but that is not implemented in FirebaseUI-iOS.
https://github.com/firebase/FirebaseUI-iOS

**Comment by robmr88** [comment]
Hi, yes I know that in the native version there is no logo for iOs but before using your library I was using another one for Flutter but unfortunately it got discontinued so I had to abandon it.
However that library managed to add the logo for iOs as well.
The library was this one:
https://pub.dev/packages/firebase_auth_ui

It's really nice to have the logo for iOs as well so I was wondering if by any chance it could be added in this library too

**Comment by koji-1009** [comment]
Well, I checked. It's the following code.
https://github.com/sam0829/firebase_auth_ui/blob/v1.0.1/ios/Classes/CustomFUIAuthPickerViewController.swift#L9

---

The policy of this library is as written at [medium post](https://koji-1009.medium.com/introduction-of-flutter-auth-ui-ad5895646f3c).
Sorry, there are no plans to add original features that are not in the library.
