### ISSUE TITLE
Signing out from firebase auth doesn't sign out from google auth (or other auth providers)

### ISSUE THREAD

**Issue by ahmednfwela** [koji-1009/flutter_auth_ui#75]
Steps to reproduce:

1. login from the authUI using google auth
2. you will get a prompt asking for your google credentials
3. After logging in successfully, logout from firebase auth
4. try logging in again using google auth
5. you will see that the prompt in step 2 doesn't come again, and instead it directly logs you in using the previously authed google account

That's why authUI added their own `signOut` that signs out from underlying providers
android: https://firebase.google.com/docs/auth/android/firebaseui#sign_out
ios: https://firebase.google.com/docs/auth/ios/firebaseui#sign_out
web: no-op as only firebase persists user credentials, and the underlying providers don't.

**Comment by koji-1009** [comment]
OK.
