### ISSUE TITLE
The process of `FlutterAuthUi.startUi()` is not completed

### ISSUE THREAD

**Issue by morio77** [koji-1009/flutter_auth_ui#76]
```dart
          onPressed: () async {
            final providers = [
              AuthUiProvider.email,
              AuthUiProvider.apple,
              AuthUiProvider.github,
            ];

            final result = await FlutterAuthUi.startUi(
              items: providers,
              tosAndPrivacyPolicy: TosAndPrivacyPolicy(
                tosUrl: 'https://www.google.com',
                privacyPolicyUrl: 'https://www.google.com',
              ),
              emailAuthOption: const EmailAuthOption(
                enableMailLink: true,
                handleURL: 'https://xxx.page.link/test',
                androidMinimumVersion: '',
                androidPackageName: 'com.example.yyy_sample',
              ),
            );

            print(result); // not executed.
          },
```

**Comment by koji-1009** [comment]
Hi, @morio77

What happens in the following two cases?
1. Set `false` to `enableMailLink`
2. Set `1` to `androidMinimumVersion`

---

Also, isn't an error log output?

**Comment by morio77** [comment]
@koji-1009 

In the following cases, there was no problem.

>Set false to enableMailLink

In the following cases, there was a problem according to the issue title.

>Set 1 to androidMinimumVersion

**Comment by koji-1009** [comment]
@morio77 
Have you finished setting up the firebase console?
https://firebase.google.com/docs/auth/android/email-link-auth#enable_email_link_sign-in_for_your_firebase_project

**Comment by morio77** [comment]
@koji-1009 

Yes, email link verification completes the login itself.

**Comment by koji-1009** [comment]
@morio77 
Oh, I see.

It probably works if you change the handleURL to the URL you want to transition to instead of dynamic links.
The document is wrong, I will fix it.

**Comment by koji-1009** [comment]
https://github.com/firebase/snippets-android/blob/8184cba2c40842a180f91dcfb4a216e721cc6ae6/auth/app/src/main/java/com/google/firebase/quickstart/auth/MainActivity.java#L340

**Comment by morio77** [comment]
@koji-1009 

When coming back to the app from the browser, the Android app was launching as another activity.

When I modified `AndroidManifest.xml` to launch the app as the same activity, this problem did not occur.

↓

https://github.com/morio77/flutter_auth_ui_sample/blob/main/android/app/src/main/AndroidManifest.xml#L8

**Comment by koji-1009** [comment]
@morio77 

Isn't that the setting in the Flutter template?
Sorry, I don't know what is being pointed out.

https://github.com/flutter/flutter/blob/2.5.0/packages/flutter_tools/templates/app_shared/android.tmpl/app/src/main/AndroidManifest.xml.tmpl#L8

**Comment by koji-1009** [comment]
@morio77 
What is the purpose of this issue?
I'm sorry, but I can't figure it out.

**Comment by morio77** [comment]
@koji-1009 

The purpose of this Issue is to report a bug that may prevent `FlutterAuthUi.startUi()` from returning.

By modifying `AndroidManifest.xml`, I was able to solve my problem, so you can close this Issue if you want.

**Comment by koji-1009** [comment]
See the commit here and change the URL to set.

https://github.com/koji-1009/flutter_auth_ui/commit/d280ca30fcee4708ce129bd5307cd2c63a33621b#diff-cb6f6bb0f943995e17737dd8710e3d814e5cebf3f58fa327c6d4c26c9df641fb
