### ISSUE TITLE
Captcha for phone login is behind Login button

### ISSUE THREAD

**Issue by MyVenueGit** [koji-1009/flutter_auth_ui#80]
Currently in flutter_auth_ui_web.dart, somehow the code add containerDiv after the body (outside body, still inside html). So when the captcha div is added inside the body, it is still behind the containerDiv.
Suggest fix: 
- Let the user decide to either use #firebaseui-auth-container or not.
- or Add the div to the end of body instead.
Thanks

**Comment by koji-1009** [comment]
I released [v1.0.7](https://pub.dev/packages/flutter_auth_ui_web/versions/1.0.7).
