### ISSUE TITLE
How can I customize view for web version?

### ISSUE THREAD

**Issue by KeisukeNagakawa** [koji-1009/flutter_auth_ui#82]
Hi, first of all, thank you for making this great library.

When I press "start ui" button, this library navigates to white & simple new page. I want to customize its view(color or location of the signin method list, etc), but I couldn't understand the proper way of doing that. 

Is there a proper way of customizing the attatched page's view for web version? Thanks!

<img width="1063" alt="スクリーンショット 2022-01-03 11 11 45" src="https://user-images.githubusercontent.com/28346899/147895622-b3e8bfb2-55ef-460d-be10-aa73881f973c.png">

**Comment by koji-1009** [comment]
Hi @KeisukeNagakawa,

Sorry, but flutter_auth_ui_web does not support customization.
To be customizable, it needs to be written in Dart, but flutter_auth_ui_web just calls a JS library.

---

On the other hand, there is a library that the firebase team implemented in Dart. 
I think the library is what you are expecting.
https://firebase.flutter.dev/docs/ui/overview/

**Comment by KeisukeNagakawa** [comment]
Thank you!
