### ISSUE TITLE
Github sign in button not shown on web

### ISSUE THREAD

**Issue by KeisukeNagakawa** [koji-1009/flutter_auth_ui#83]
Hi I'm using exampe web app but github sign in button is not shown. Is there any way to fix this? Thanks
![スクリーンショット 2022-01-03 12 05 53](https://user-images.githubusercontent.com/28346899/147897175-4493dc81-a5b9-4e66-994c-b457f0f0371f.png)
<img width="363" alt="スクリーンショット 2022-01-03 12 06 00" src="https://user-images.githubusercontent.com/28346899/147897178-d94cbf49-f9a9-48d4-8548-151516f57526.png">
!

**Comment by koji-1009** [comment]
Thanks! It's my bad!

https://github.com/koji-1009/flutter_auth_ui/blob/2.4.1/flutter_auth_ui/lib/flutter_auth_ui.dart#L65
https://github.com/koji-1009/flutter_auth_ui/blob/2.4.1/flutter_auth_ui_web/lib/flutter_auth_ui_web.dart#L78
