### ISSUE TITLE
Support for PopUp sign in

### ISSUE THREAD

**Issue by naveenc78** [koji-1009/flutter_auth_ui#86]
Thanks for the library. Very useful. It seems support for pop up sign in is not incorporated into this - defaults to redirect. Can this be made available?

**Comment by koji-1009** [comment]
Hi @naveenc78 ,

Currently, the default behavior is set to `popup`.
https://github.com/koji-1009/flutter_auth_ui/blob/2.4.2/flutter_auth_ui_web/lib/flutter_auth_ui_web.dart#L136

If you get redirected, it may be blocked by your browser, or there may be a lack of implementation on this package.
Could you tell me which providers do not launch popup?
https://github.com/firebase/firebaseui-web#sign-in-flows

(However, please be aware that the implementation of for web is difficult and may not be possible.)

**Comment by naveenc78** [comment]
Thanks much for your reply. Apologies for the delayed response. All providers (most of the ones I use) are loading as pop up but what I was referring to is the screen that lists all the providers available is a page itself and not an overlay on the existing one. That makes it feel disjointed with the experience. I am not sure if I am doing something incorrect, I am calling the startui function from an async onpressed function from the Sign in button. 

Also, secondly, is there a way for the web implementation to include the call back locations like the ioS/Android versions do? Thank you so much!

**Comment by koji-1009** [comment]
Hmmm...
I'm sorry, but I don't plan to investigate how to support popup mode.

How about using flutterfire_ui?
https://pub.dev/packages/flutterfire_ui
